name = "zabaan-v3"
main = "src/worker.js"
compatibility_date = "2026-09-24"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "ZABAAN_KV"
id = "b24b460bfe7349fea047c6c929f3cf59"
